### ISSUE TITLE
Paramaetrize sleep time

### ISSUE THREAD

**Issue by ammsa** [zechamkank/downtime-twitter-bot#1]
Not an issue but more of a suggestion. The code [here](https://github.com/zechamkank/downtime-twitter-bot/blob/master/bot.py#L40) set 60 seconds as the wait time before sending another request. This might be too expensive/too slow/too long, etc depending on the user. I suggest you add the option to set it in an argument. 

Something like 

`python bot.py --wait-time 216000` or even better `python bot.py --wait-time 1 hour`

Cheers!

**Comment by chamkank** [comment]
Hey, thanks for taking the time to post this! I've just made some changes, putting the polling time as another constant the user can change.

I'll implement the command-line arguments as suggested and some logging features when I get home. Thanks again for your feedback!

**Comment by chamkank** [comment]
# 4baabb1c94bd29b688abbe3d633021ccc9023bb5
